import axios from "axios"
import { useEffect } from "react"


import { useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'
import './enhancements.css'

type AssetStatus = 'Available' | 'Allocated' | 'Reserved' | 'Under Maintenance' | 'Lost' | 'Retired'
type Asset = { tag: string; name: string; category: string; department: string; location: string; condition: string; status: AssetStatus; holder?: string; returnDate?: string; health: number }

const initialAssets: Asset[] = [
  { tag: 'AF-0001', name: 'Dell Latitude 7440', category: 'Electronics', department: 'Engineering', location: 'Bengaluru HQ', condition: 'Excellent', status: 'Allocated', holder: 'Heer', returnDate: '2026-07-09', health: 88 },
  { tag: 'AF-0002', name: 'Sony Conference Camera', category: 'Electronics', department: 'Operations', location: 'Meeting Room B2', condition: 'Good', status: 'Available', health: 92 },
  { tag: 'AF-0003', name: 'Epson EB-X49 Projector', category: 'Electronics', department: 'Marketing', location: 'Mumbai Office', condition: 'Good', status: 'Under Maintenance', health: 58 },
  { tag: 'AF-0004', name: 'Toyota Innova', category: 'Vehicles', department: 'Operations', location: 'Bengaluru HQ', condition: 'Good', status: 'Reserved', health: 84 },
  { tag: 'AF-0005', name: 'Herman Miller Chair', category: 'Furniture', department: 'HR', location: 'Bengaluru HQ', condition: 'Fair', status: 'Available', health: 64 },
]

const nav = [
  ['Dashboard', '⌂'], ['Organization Setup', '◫'], ['Assets', '▣'], ['Allocation & Transfer', '⇄'], ['Resource Booking', '◷'], ['Maintenance', '⚒'], ['Asset Audit', '✓'], ['Reports & Analytics', '▥'], ['Notifications', '♢'],
]

function statusClass(status: string) { return status.toLowerCase().replaceAll(' ', '-') }
function Badge({ value }: { value: string }) { return <span className={`badge ${statusClass(value)}`}>{value}</span> }

export default function App() {
  const [authenticated, setAuthenticated] = useState(false)
  const [profileOpen, setProfileOpen] = useState(false)
  const [unreadCount, setUnreadCount] = useState(3)
  const [page, setPage] = useState('Dashboard')
  const [assets, setAssets] = useState<Asset[]>(initialAssets)
  const [query, setQuery] = useState('')
  const [modal, setModal] = useState<'asset' | 'allocate' | 'maintenance' | null>(null)
  const [notice, setNotice] = useState('')
  const [activities, setActivities] = useState(['Asset AF-0002 was registered by Vijay', 'Maintenance request created for AF-0003 by Hima', 'AF-0004 was booked by Dhruv for 12 July'])
  const visibleAssets = useMemo(() => assets.filter(a => `${a.tag} ${a.name} ${a.status} ${a.department}`.toLowerCase().includes(query.toLowerCase())), [assets, query])
  const available = assets.filter(a => a.status === 'Available').length
  const allocated = assets.filter(a => a.status === 'Allocated').length
  const maintenance = assets.filter(a => a.status === 'Under Maintenance').length
  const toast = (message: string) => { setNotice(message); setTimeout(() => setNotice(''), 3500) }
  useEffect(() => {
  const loadDashboard = async () => {
    try {
      const { data } = await axios.get(
        'http://localhost:8080/api/dashboard'
      )

      console.log('Dashboard API:', data)

      if (data.assets) {
        setAssets(data.assets)
      }

      if (data.recentActivities) {
        setActivities(
          data.recentActivities.map((a: any) => a.message)
        )
      }

      toast('Dashboard synced with Spring Boot API')
    } catch (err) {
      console.error('Dashboard API Error:', err)
      toast('Backend unavailable. Using demo data.')
    }
  }

  loadDashboard()
}, [])
  function addAsset(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const data = new FormData(e.currentTarget)
    const tag = `AF-${String(assets.length + 1).padStart(4, '0')}`
    setAssets([{ tag, name: String(data.get('name')), category: String(data.get('category')), department: String(data.get('department')), location: String(data.get('location')), condition: 'Good', status: 'Available', health: 100 }, ...assets])
    setActivities([`${tag} was registered by Asset Manager`, ...activities]); setModal(null); toast(`${tag} registered and available for allocation.`)
  }
  function allocate(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const data = new FormData(e.currentTarget); const tag = String(data.get('asset')); const holder = String(data.get('holder')); const due = String(data.get('due'))
    const item = assets.find(a => a.tag === tag)
    if (!item || item.status !== 'Available') { toast(`Allocation blocked: ${item?.tag ?? 'Asset'} is currently ${item?.status.toLowerCase() ?? 'unavailable'}. Create a transfer request instead.`); return }
    setAssets(assets.map(a => a.tag === tag ? { ...a, status: 'Allocated', holder, returnDate: due } : a)); setActivities([`${tag} allocated to ${holder}`, ...activities]); setModal(null); toast(`${tag} allocated successfully. Dashboard and notifications updated.`)
  }
  function raiseMaintenance(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const data = new FormData(e.currentTarget); const tag = String(data.get('asset'))
    setAssets(assets.map(a => a.tag === tag ? { ...a, status: 'Under Maintenance' } : a)); setActivities([`Maintenance approved for ${tag}; asset moved to Under Maintenance`, ...activities]); setModal(null); toast('Maintenance request approved. Asset status changed to Under Maintenance.')
  }
  function renderContent() {
    if (page === 'Dashboard') return <Dashboard available={available} allocated={allocated} maintenance={maintenance} assets={assets} activities={activities} open={setModal} />
    if (page === 'Assets') return <Assets assets={visibleAssets} query={query} setQuery={setQuery} open={setModal} />
    if (page === 'Allocation & Transfer') return <Allocation assets={assets} open={setModal} onReturn={(tag: string) => { setAssets(assets.map(a => a.tag === tag ? { ...a, status: 'Available', holder: undefined, returnDate: undefined } : a)); toast(`${tag} returned and now available.`) }} />
    if (page === 'Maintenance') return <Maintenance assets={assets} open={setModal} resolve={(tag: string) => { setAssets(assets.map(a => a.tag === tag ? { ...a, status: 'Available', health: Math.min(100, a.health + 8) } : a)); toast(`${tag} resolved and returned to Available.`) }} />
    if (page === 'Organization Setup') return <Organization />
    if (page === 'Resource Booking') return <Booking toast={toast} />
    if (page === 'Asset Audit') return <Audit toast={toast} />
    if (page === 'Reports & Analytics') return <Reports assets={assets} />
    return <Notifications activities={activities} unreadCount={unreadCount} markRead={()=>setUnreadCount(0)} />
  }
  if (!authenticated) return <Login onLogin={() => setAuthenticated(true)} />
  return <div className="app-shell">
    <aside><div className="brand"><img src="/assetflow-logo.svg" alt="AssetFlow"/><div>AssetFlow <small>ERP PLATFORM</small></div></div><div className="workspace">WORKSPACE</div>{nav.map(([label, icon]) => <button key={label} className={page === label ? 'nav active' : 'nav'} onClick={() => setPage(label)}><i>{icon}</i>{label}{label === 'Notifications' && unreadCount > 0 && <b>{unreadCount}</b>}</button>)}<div className="profile-wrap"><button className="profile" onClick={()=>setProfileOpen(!profileOpen)}><div className="avatar">VR</div><div><strong>Vijay</strong><small>Asset Manager</small></div><span>⌄</span></button>{profileOpen&&<div className="profile-menu"><button onClick={()=>{setPage('Organization Setup');setProfileOpen(false)}}>Account settings</button><button onClick={()=>{setAuthenticated(false);setProfileOpen(false)}}>Sign out</button></div>}</div></aside>
    <main><header><div><p className="crumb">AssetFlow / {page}</p><h1>{page}</h1></div><div className="head-actions"><button className="icon-btn" onClick={()=>toast('Global search will be available with the connected API.')}>⌕</button><button className="icon-btn" onClick={()=>setPage('Notifications')}>♢{unreadCount>0&&<em>{unreadCount}</em>}</button><button className="help" onClick={()=>toast('Use the sidebar to move between asset operations.')}>?</button></div></header>{notice && <div className="toast">✓ {notice}</div>}{page === 'Notifications' ? <Notifications activities={activities} unreadCount={unreadCount} markRead={()=>setUnreadCount(0)}/> : renderContent()}</main>
    {modal === 'asset' && <Modal title="Register New Asset" close={() => setModal(null)}><form onSubmit={addAsset}><Field label="Asset name" name="name" placeholder="e.g. Dell Latitude 7440" required/><div className="form-row"><Select label="Category" name="category" options={['Electronics', 'Furniture', 'Vehicles']} /><Select label="Department" name="department" options={['Engineering', 'HR', 'Operations', 'Marketing']} /></div><Field label="Location" name="location" placeholder="e.g. Bengaluru HQ" required/><div className="form-actions"><button type="button" className="secondary" onClick={() => setModal(null)}>Cancel</button><button>Register Asset</button></div></form></Modal>}
    {modal === 'allocate' && <Modal title="Allocate Asset" close={() => setModal(null)}><form onSubmit={allocate}><Select label="Available asset" name="asset" options={assets.filter(a => a.status === 'Available').map(a => `${a.tag} - ${a.name}`)} valueOnly /><Field label="Employee name" name="holder" placeholder="e.g. Rahul Mehta" required/><Field label="Expected return date" name="due" type="date" required/><p className="hint">Unavailable assets are protected from double-allocation. Use a transfer request when an asset already has a holder.</p><div className="form-actions"><button type="button" className="secondary" onClick={() => setModal(null)}>Cancel</button><button>Confirm Allocation</button></div></form></Modal>}
    {modal === 'maintenance' && <Modal title="Raise Maintenance Request" close={() => setModal(null)}><form onSubmit={raiseMaintenance}><Select label="Asset" name="asset" options={assets.filter(a => !['Retired', 'Lost'].includes(a.status)).map(a => `${a.tag} - ${a.name}`)} valueOnly /><Select label="Priority" name="priority" options={['High', 'Medium', 'Low']} /><label>Issue description<textarea name="description" placeholder="Describe the issue clearly" required /></label><div className="form-actions"><button type="button" className="secondary" onClick={() => setModal(null)}>Cancel</button><button>Submit Request</button></div></form></Modal>}
  </div>
}

function Dashboard({ available, allocated, maintenance, assets, activities, open }: any) { const overdue = assets.filter((a: Asset) => a.returnDate && a.returnDate < '2026-07-12'); return <><section className="quick"><button onClick={() => open('asset')}>＋ Register Asset</button><button onClick={() => open('allocate')}>⇄ Allocate Asset</button><button onClick={() => open('maintenance')}>⚒ Raise Maintenance</button></section><section className="kpis"><Kpi label="Assets Available" value={available} icon="▣" tone="purple"/><Kpi label="Assets Allocated" value={allocated} icon="⇄" tone="blue"/><Kpi label="Maintenance Today" value={maintenance} icon="⚒" tone="orange"/><Kpi label="Active Bookings" value="2" icon="◷" tone="green"/><Kpi label="Pending Transfers" value="1" icon="⇄" tone="pink"/><Kpi label="Upcoming Returns" value="2" icon="↩" tone="yellow"/></section><section className="grid two"><Panel title="Asset Status Overview" action="View assets"><div className="donut-wrap"><div className="donut"><span>{assets.length}<small>TOTAL</small></span></div><div className="legend"><p><i className="dot available"/>Available <b>{available}</b></p><p><i className="dot allocated"/>Allocated <b>{allocated}</b></p><p><i className="dot maintenance"/>Maintenance <b>{maintenance}</b></p><p><i className="dot reserved"/>Reserved <b>1</b></p></div></div></Panel><Panel title="Manager Action Center" action="Prioritized"><div className="actions"><Action color="red" text={`${overdue.length || 1} overdue return needs follow-up`} sub="AF-0001 • Priya Shah"/><Action color="orange" text="1 maintenance request awaiting review" sub="Epson Projector AF-0003"/><Action color="yellow" text="1 low-health asset needs attention" sub="Herman Miller Chair • 64% health"/><Action color="blue" text="1 transfer request pending approval" sub="Laptop AF-0001 • Engineering"/></div></Panel></section><section className="grid two lower"><Panel title="Asset Health Watchlist" action="View all">{assets.sort((a: Asset,b: Asset) => a.health-b.health).slice(0,3).map((a: Asset) => <div className="health" key={a.tag}><div><strong>{a.name}</strong><small>{a.tag} · {a.condition} condition</small></div><div><b>{a.health}%</b><div className="bar"><i style={{width:`${a.health}%`}} /></div></div></div>)}</Panel><Panel title="Recent Activity" action="View log">{activities.slice(0,3).map((a: string, i: number) => <div className="activity" key={a}><span>{i === 0 ? '▣' : i === 1 ? '⚒' : '◷'}</span><p>{a}<small>{i + 1} hour{i ? 's' : ''} ago</small></p></div>)}</Panel></section></> }
function Kpi({label,value,icon,tone}: any) { return <div className="kpi"><span className={tone}>{icon}</span><div><small>{label}</small><strong>{value}</strong><p>Live from PostgreSQL</p></div></div> }
function Panel({title, action, children}: any) { return <section className="panel"><div className="panel-head"><h2>{title}</h2><button>{action} →</button></div>{children}</section> }
function Action({color,text,sub}: any) { return <div className="action"><i className={color}/><div><strong>{text}</strong><small>{sub}</small></div><button>Review →</button></div> }
function Assets({assets,query,setQuery,open}: any) {return <><section className="toolbar"><div><h2>Asset Directory</h2><p>Register, locate and manage every organizational asset.</p></div><button onClick={() => open('asset')}>＋ Register Asset</button></section><section className="panel table-panel"><div className="filters"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search by asset tag, name, category..."/><select><option>All categories</option><option>Electronics</option><option>Furniture</option></select><select><option>All statuses</option><option>Available</option><option>Allocated</option></select></div><AssetTable assets={assets}/></section></>}
function AssetTable({assets}: {assets: Asset[]}) {return <table><thead><tr><th>ASSET</th><th>CATEGORY</th><th>LOCATION</th><th>HOLDER</th><th>HEALTH</th><th>STATUS</th><th></th></tr></thead><tbody>{assets.map(a => <tr key={a.tag}><td><strong>{a.name}</strong><small>{a.tag} · {a.condition}</small></td><td>{a.category}</td><td>{a.location}</td><td>{a.holder || '—'}</td><td><span className="health-mini">{a.health}%</span></td><td><Badge value={a.status}/></td><td><button className="more">•••</button></td></tr>)}</tbody></table>}
function Allocation({assets,open,onReturn}: any) {return <><section className="toolbar"><div><h2>Allocation & Transfer</h2><p>Assign assets, approve transfers and track expected returns.</p></div><button onClick={() => open('allocate')}>＋ Allocate Asset</button></section><section className="panel table-panel"><div className="callout"><b>Conflict protection is active.</b> An asset with an active allocation cannot be allocated again. The user is guided to create a transfer request.</div><table><thead><tr><th>ASSET</th><th>CURRENT HOLDER</th><th>DEPARTMENT</th><th>EXPECTED RETURN</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{assets.filter((a:Asset)=>a.status==='Allocated').map((a:Asset)=><tr key={a.tag}><td><strong>{a.name}</strong><small>{a.tag}</small></td><td>{a.holder}</td><td>{a.department}</td><td className={a.returnDate! < '2026-07-12' ? 'overdue' : ''}>{a.returnDate} {a.returnDate! < '2026-07-12' && 'Overdue'}</td><td><Badge value="Allocated"/></td><td><button className="link" onClick={()=>onReturn(a.tag)}>Mark returned</button></td></tr>)}</tbody></table></section></>}
function Maintenance({assets,open,resolve}: any) { const items = assets.filter((a:Asset)=>a.status==='Under Maintenance'); return <><section className="toolbar"><div><h2>Maintenance Management</h2><p>Approval-driven repairs with a traceable lifecycle.</p></div><button onClick={() => open('maintenance')}>＋ Raise Request</button></section><div className="kanban five"><Kanban title="Pending" count={1}><Card tag="AF-0005" title="Chair armrest damage" priority="Medium"/></Kanban><Kanban title="Approved" count={1}><Card tag="AF-0011" title="Scanner calibration" priority="Low"/></Kanban><Kanban title="Technician Assigned" count={1}><Card tag="AF-0078" title="Forklift service" priority="High"/></Kanban><Kanban title="In Progress" count={items.length}>{items.map((a:Asset)=><Card key={a.tag} tag={a.tag} title={a.name} priority="High" action={()=>resolve(a.tag)} />)}</Kanban><Kanban title="Resolved" count={1}><Card tag="AF-0087" title="Printer paper-feed repair" priority="Low"/></Kanban></div><p className="workflow-note">Approving a request moves the asset to <b>Under Maintenance</b>. Resolving it returns the asset to <b>Available</b>.</p></> }
function Kanban({title,count,children}:any){return <section className="kanban-col"><h3>{title}<b>{count}</b></h3>{children}</section>}; function Card({tag,title,priority,action}:any){return <div className="maintenance-card"><Badge value={priority}/><strong>{title}</strong><small>{tag} · Updated today</small>{action && <button className="link" onClick={action}>Mark resolved →</button>}</div>}
function Organization(){const [tab,setTab]=useState('Departments'); const content = tab==='Departments' ? {heads:['DEPARTMENT','DEPARTMENT HEAD','PARENT DEPARTMENT','STATUS'],rows:[['Engineering','Heer','—','Active'],['Facilities','Dhruv','—','Active'],['Field Ops (East)','Hima','Field Ops','Inactive']]} : tab==='Asset Categories' ? {heads:['CATEGORY','WARRANTY','BOOKABLE DEFAULT','STATUS'],rows:[['Electronics','24 months','Yes','Active'],['Furniture','12 months','No','Active'],['Vehicles','36 months','Yes','Active']]} : {heads:['EMPLOYEE','DEPARTMENT','ROLE','STATUS'],rows:[['Vijay','Operations','Asset Manager','Active'],['Heer','Engineering','Department Head','Active'],['Hima','Field Ops','Employee','Active'],['Dhruv','Facilities','Employee','Active']]}; return <><section className="toolbar"><div><h2>Organization Setup</h2><p>Admin-only master data. Updates are available across allocation and registration forms.</p></div><button onClick={()=>alert(`Add ${tab === 'Departments' ? 'Department' : tab === 'Asset Categories' ? 'Category' : 'Employee'} form is ready for backend connection.`)}>＋ Add</button></section><section className="tabs">{['Departments','Asset Categories','Employee Directory'].map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?'selected':''}>{t}</button>)}</section><section className="panel table-panel"><table><thead><tr>{content.heads.map(h=><th key={h}>{h}</th>)}<th></th></tr></thead><tbody>{content.rows.map(r=><tr key={r[0]}>{r.map((x,i)=><td key={i}>{i===0?<strong>{x}</strong>:i===r.length-1?<Badge value={x}/>:x}</td>)}<td><button className="more" title="Edit record">•••</button></td></tr>)}</tbody></table></section><p className="screen-note">{tab==='Departments'?'Editing a department updates the allocation and asset-registration picklists.':tab==='Asset Categories'?'Category rules such as warranty and bookability are managed here.':'Only an admin can promote an Employee to Asset Manager or Department Head.'}</p></>}
function Booking({toast}:any){const [showForm,setShowForm]=useState(false);const [start,setStart]=useState('09:30');const [end,setEnd]=useState('10:30');const [bookings,setBookings]=useState([{start:'09:00',end:'10:00',title:'Product Review',owner:'Heer'},{start:'11:00',end:'12:00',title:'Team Stand-up',owner:'Dhruv'},{start:'14:00',end:'15:30',title:'Client Workshop',owner:'Hima'}]);const conflict=bookings.some(b=>start<b.end&&end>b.start);function create(e:FormEvent){e.preventDefault();if(end<=start){toast('Booking rejected: end time must be after start time.');return}if(conflict){toast('Booking rejected: Meeting Room B2 is already reserved during this time.');return}setBookings([...bookings,{start,end,title:'New resource booking',owner:'Vijay'}]);setShowForm(false);toast(`Booking confirmed for ${start} - ${end}.`)}return <><section className="toolbar"><div><h2>Resource Booking</h2><p>Book shared assets without scheduling conflicts.</p></div><button onClick={()=>setShowForm(!showForm)}>{showForm?'Close form':'＋ Create Booking'}</button></section>{showForm&&<section className="panel booking-form"><h2>Create booking</h2><form onSubmit={create}><div className="form-row"><label>Start time<input type="time" value={start} onChange={e=>setStart(e.target.value)} required/></label><label>End time<input type="time" value={end} onChange={e=>setEnd(e.target.value)} required/></label></div><label>Purpose<input placeholder="e.g. Product review" required/></label><p className={conflict?'validation bad':'validation ok'}>{conflict?'This overlaps an existing booking.':'This slot is available.'}</p><div className="form-actions"><button type="button" className="secondary" onClick={()=>setShowForm(false)}>Cancel</button><button>Create booking</button></div></form></section>}<section className="panel booking-calendar"><div className="panel-head"><div><h2>Meeting Room B2 - Today</h2><p>Calendar view · Shared resource</p></div><button onClick={()=>toast('Calendar is showing today’s confirmed resource bookings.')}>Today</button></div><div className="schedule">{bookings.map(b=><p key={`${b.start}${b.title}`}><b>{b.start} - {b.end}</b><span>{b.title} · {b.owner}</span></p>)}</div></section></>}
function Audit({toast}:any){const [closed,setClosed]=useState(false);return <><section className="toolbar"><div><h2>Asset Audit</h2><p>Run verification cycles and resolve discrepancies.</p></div><button onClick={()=>toast('New audit cycle created for Bengaluru HQ.')}>＋ Create Audit Cycle</button></section><section className="panel"><div className="audit-head"><div><Badge value={closed?'Closed':'In Progress'}/><h2>Q3 Bengaluru HQ Verification</h2><p>Auditors: Megha Patel, Rohan Das · Due 18 July</p></div><button onClick={()=>toast('Discrepancy report downloaded.')}>Export discrepancy report</button></div><table className="audit-table"><thead><tr><th>ASSET</th><th>EXPECTED LOCATION</th><th>VERIFICATION</th></tr></thead><tbody><tr><td>AF-0003 Dell Laptop</td><td>Desk E12</td><td><Badge value="Verified"/></td></tr><tr><td>AF-0021 Office Chair</td><td>Desk E14</td><td><Badge value="Missing"/></td></tr><tr><td>AF-0088 Monitor</td><td>Desk E15</td><td><Badge value="Damaged"/></td></tr></tbody></table><div className="audit-footer"><div className="discrepancy">2 assets flagged - discrepancy report generated automatically.</div><button disabled={closed} onClick={()=>{setClosed(true);toast('Audit cycle closed. Missing assets are marked for review.')}}>{closed?'Audit cycle closed':'Close audit cycle'}</button></div></section></>}
function Reports({assets}:any){function exportCsv(){const csv=['Asset Tag,Asset Name,Status,Health',...assets.map((a:Asset)=>`${a.tag},${a.name},${a.status},${a.health}%`)].join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='assetflow-report.csv';a.click();URL.revokeObjectURL(url)}return <><section className="toolbar"><div><h2>Reports & Analytics</h2><p>Operational insight based on live AssetFlow data.</p></div><button onClick={exportCsv}>⇩ Export CSV</button></section><section className="grid two"><Panel title="Asset utilization by department" action=""><div className="bars">{['Engineering','Operations','Marketing','HR'].map((x,i)=><p key={x}><span>{x}</span><i style={{width:`${88-i*17}%`}}/></p>)}</div></Panel><Panel title="Maintenance frequency" action=""><div className="report-metrics"><p><strong>{assets.filter((a:Asset)=>a.health<70).length}</strong> Assets need attention</p><p><strong>1</strong> Repair in progress</p><p><strong>92%</strong> Average asset health</p></div></Panel></section><section className="panel report-list"><h2>Operational highlights</h2><p><b>Most used:</b> Sony Conference Camera AF-0002 - 34 bookings this month</p><p><b>Idle assets:</b> Herman Miller Chair AF-0005 - unused for 45 days</p><p><b>Due for review:</b> Epson Projector AF-0003 - health score below 60%</p></section></>}
function Notifications({activities,unreadCount,markRead}:any){const [filter,setFilter]=useState('All');const list=activities.concat(['Transfer request awaiting your approval','Overdue return alert sent to Heer','Booking confirmed: Meeting Room B2, 2:00 - 3:00 PM']);return <section className="panel notifications"><div className="panel-head"><div><h2>Notifications & Activity Log</h2><p className="notification-caption">{unreadCount?`${unreadCount} unread notifications`:'All notifications are read'}</p></div><button onClick={markRead} disabled={!unreadCount}>Mark all as read</button></div><div className="tabs notif-tabs">{['All','Alerts','Approvals','Bookings'].map(t=><button key={t} onClick={()=>setFilter(t)} className={filter===t?'selected':''}>{t}</button>)}</div>{list.filter((x:string)=>filter==='All'||filter==='Alerts'&&x.includes('Overdue')||filter==='Approvals'&&x.includes('request')||filter==='Bookings'&&x.includes('Booking')).map((x:string,i:number)=><div className="notification" key={x}><span>{i<2?'⚒':'▣'}</span><div><strong>{x}</strong><small>{i+1} hour{i?'s':''} ago · AssetFlow automation</small></div><i className={i<unreadCount?'unread':''}/></div>)}</section>}
function Login({onLogin}:{onLogin:()=>void}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [error,setError]=useState('');const [mode,setMode]=useState<'login'|'signup'>('login');function submit(e:FormEvent){e.preventDefault();const validEmail=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);const strongPassword=password.length>=8&&/[A-Z]/.test(password)&&/[a-z]/.test(password)&&/\d/.test(password);if(!validEmail){setError('Enter a valid work email address.');return}if(!strongPassword){setError('Password must contain 8+ characters, an uppercase letter, a lowercase letter, and a number.');return}if(mode==='signup'&&password!==confirm){setError('Passwords do not match.');return}setError('');onLogin()}return <main className="login-page"><section className="login-card"><div className="login-brand"><img src="/assetflow-logo.svg" alt="AssetFlow logo"/><div><strong>AssetFlow</strong><small>ENTERPRISE ASSET OPERATIONS</small></div></div><div className="login-copy"><h1>{mode==='login'?'Welcome back':'Create your account'}</h1><p>{mode==='login'?'Sign in to manage your organization’s assets and resources.':'Create an Employee account. An administrator can assign elevated roles later.'}</p></div><form onSubmit={submit} noValidate><label>Work email<input type="email" value={email} onChange={e=>setEmail(e.target.value.trimStart())} placeholder="name@company.com" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="8+ characters, upper/lowercase + number" required/></label>{mode==='signup'&&<label>Confirm password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Re-enter your password" required/></label>}{error&&<p className="form-error">{error}</p>}<button className="login-submit">{mode==='login'?'Sign in to AssetFlow':'Create Employee Account'}</button></form><div className="login-foot">{mode==='login'?<>New here? <button onClick={()=>{setMode('signup');setError('')}}>Create an Employee account</button></>:<>Already registered? <button onClick={()=>{setMode('login');setError('')}}>Sign in instead</button></>}</div></section></main>}
function Modal({title,close,children}:any){return <div className="modal-backdrop"><section className="modal"><div className="modal-head"><h2>{title}</h2><button onClick={close}>×</button></div>{children}</section></div>}; function Field({label,name,placeholder,required,type='text'}:any){return <label>{label}<input name={name} placeholder={placeholder} required={required} type={type}/></label>}; function Select({label,name,options,valueOnly}:any){return <label>{label}<select name={name}>{options.map((x:string)=><option value={valueOnly?x.split(' - ')[0]:x} key={x}>{x}</option>)}</select></label>}
